jwt.secret-key=${JWT_SECRET_KEY}
jwt.expiration=${JWT_ACCESS_EXPIRATION_MS:900000}
jwt.refresh-token-expiration=${JWT_REFRESH_EXPIRATION_MS:604800000}
jwt.issuer=${JWT_ISSUER:manager-v2}
jwt.audience=${JWT_AUDIENCE:manager-v2-gui}
auth.cookie.secure=true


refreshtoken.key=${REFRESH_TOKEN_KEY}
refreshtoken.delete = 0 0 * * * *
