# Secret key only for dev local tests
jwt.secret-key=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expiration=${JWT_ACCESS_EXPIRATION_MS:900000}
jwt.refresh-token-expiration=${JWT_REFRESH_EXPIRATION_MS:604800000}
jwt.issuer=${JWT_ISSUER:manager-v2}
jwt.audience=${JWT_AUDIENCE:manager-v2-gui}
auth.cookie.secure=false


refreshtoken.key= refreshtokenkey
refreshtoken.delete = 0 0 * * * *
