ALTER TABLE department
    ADD COLUMN department_type VARCHAR(50) NOT NULL DEFAULT 'BRANCH',
    ADD COLUMN created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    ADD COLUMN updated_at TIMESTAMP NOT NULL DEFAULT NOW();
