//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.01.16 at 08:51:01 PM CET 
//


package com.warehouse.zebra.model.parcel_created_request;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the parcel_created_request package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ParcelCreatedRequest_QNAME = new QName("com/warehouse/zebra/model/parcel_created_request", "ParcelCreatedRequest");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: parcel_created_request
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ParcelCreatedRequest }
     * 
     */
    public ParcelCreatedRequest createParcelCreatedRequest() {
        return new ParcelCreatedRequest();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ParcelCreatedRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "com/warehouse/zebra/model/parcel_created_request", name = "ParcelCreatedRequest")
    public JAXBElement<ParcelCreatedRequest> createParcelCreatedRequest(ParcelCreatedRequest value) {
        return new JAXBElement<ParcelCreatedRequest>(_ParcelCreatedRequest_QNAME, ParcelCreatedRequest.class, null, value);
    }

}
