//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.01.16 at 08:51:01 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "com/warehouse/zebra/model/parcel_created_request", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.warehouse.zebra.model.parcel_created_request;
