version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: dev
      MYSQL_USER: root
      MYSQL_PASSWORD:
    ports:
      - "3306:3306"
    networks:
      - my_network

  mongodb:
    image: mongo:latest
    container_name: warehouse
    ports:
      - "27017:27017"
    networks:
      - my_network

  ManagerApplication:
    image: your-8080-app-image:latest
    container_name: ManagerApp
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    networks:
      - my_network

  SoftwareConfiguration:
    image: your-8081-app-image:latest
    container_name: spring-boot-app-8081-container
    ports:
      - "8081:8081"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
