version: "3.8"

services:
  postgresdb:
    image: postgres:13
    restart: unless-stopped
    env_file: ./.env
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=application
    ports:
      - 5432:5432
    volumes:
      - liquibase:/var/lib/postgresql/data

  app:
    depends_on:
      - postgresdb
    build: ./inparcel-app
    restart: on-failure
    env_file: ./.env
    ports:
      - 5432:5432
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:postgresql://postgresdb:5432/application",
        "spring.datasource.username" : "$POSTGRESDB_USER",
        "spring.datasource.password" : "$POSTGRESDB_ROOT_PASSWORD",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.PostgreSQLDialect",
        "spring.jpa.hibernate.ddl-auto" : "update"
      }'
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true

volumes:
  db:
