server:
  servlet:
    contextPath: /v2/api
local:
  server:
    port: 8080

shipment:
  url: http://localhost:8080
  name: shipment
  endpoint: shipments

mail:
  subject: Państwa zwracana przesyłka została odebrana przez kuriera
  message: Państwa przesyłka o numerze %s została odebrana przez kuriera \n Trafi do magazynu a następnie zostanie odesłana do nadawcy %s

service:
  mock: true