parcel:
  endpoint: parcel-updates
  url: http://localhost:8080
  port: 8080

server:
  servlet:
    contextPath: /v2/api
local:
  server:
    port: 8080

route:
  endpoint: routes
  url: http://localhost
  port: 8080

service:
  mock: true