<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                  xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                  xmlns:tns="http://example.org/zebra"
                  targetNamespace="http://example.org/zebra"
                  name="ZebraService">
    <wsdl:types>
        <xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://example.org/zebra"
                   elementFormDefault="qualified">
            <xs:import namespace="http://example.org/delivery-create"
                       schemaLocation="classpath:/schemas/supplyoperation.xsd"/>
        </xs:schema>
    </wsdl:types>
    <wsdl:message name="ZebraRequest">
        <wsdl:part name="parameters" element="tns:ZebraRequest"/>
    </wsdl:message>
    <wsdl:message name="ZebraResponse">
        <wsdl:part name="parameters" element="tns:ZebraResponse"/>
    </wsdl:message>
    <wsdl:portType name="ZebraPortType">
        <wsdl:operation name="processZebraRequest">
            <wsdl:input message="tns:ZebraRequest"/>
            <wsdl:output message="tns:ZebraResponse"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="ZebraBinding" type="tns:ZebraPortType">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="processZebraRequest">
            <soap:operation soapAction=""/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:service name="ZebraService">
        <wsdl:port name="ZebraPort" binding="tns:ZebraBinding">
            <soap:address location="http://localhost:8080/zebra"/>
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>
