##### Environment
logging.level.org.springframework.boot.context.config=DEBUG
spring.profiles.active=dev
spring.profiles.include=mail

##### Database configuration
spring.liquibase.change-log=classpath:/changelog/db.changelog-master.xml

##### Swagger
spring.mvc.pathmatch.matching-strategy= ANT_PATH_MATCHER


##### Global prefix endpoint
server.servlet.contextPath=/v2/api

##### API exposure
api.exposure.internal-prefix=/internal
api.exposure.internal-controller-paths[0]=/device-pairings
api.exposure.internal-controller-paths[1]=/device-pairing-verifications
api.exposure.pair-key-controller-paths[0]=/device-pairing-verifications
api.exposure.public-endpoints[0].method=POST
api.exposure.public-endpoints[0].path=/device-pairings

purge.cron.expression= @midnight
