##### Spring database configuration
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/dev}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}
spring.jpa.hibernate.ddl-auto=none
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:/changelog/db.changelog-master.xml
credentials.encryption-key=${CREDENTIALS_ENCRYPTION_KEY:4d616e616765725465737443726564656e7469616c456e6372797074696f6e21}





services.mock = true
return.url=${RETURNING_SERVICE_URL}
return.endpoint=${RETURNING_SERVICE_ENDPOINT}
eureka.client.enabled=false
