##### Docker service URLs
routelog.url=http://route-tracker:8082/v2/api/routes
software.url=http://software-configuration:8081
shipment.url=http://manager-application:8080
returntoken.url=http://manager-application:8080
return.url=http://returning-manager:8070
