package com.warehouse.dangerousgood.domain.enumeration;

public enum ClassificationCode {
    EXPLOSIVES,
    GASES,
    FLAMMABLE_LIQUIDS,
    FLAMMABLE_SOLIDS,
    SPONTANEOUSLY_COMBUSTIBLE,
    DANGEROUS_WHEN_WET,
    OXIDIZING_SUBSTANCES,
    ORGANIC_PEROXIDES,
    TOXIC_SUBSTANCES,
    INFECTIOUS_SUBSTANCES,
    RADIOACTIVE_MATERIAL,
    CORROSIVE_SUBSTANCES,
    MISCELLANEOUS_DANGEROUS_GOODS;
}
