##### Docker service URLs
routelog.url=http://route-tracker:8082
software.url=http://software-configuration:8081
shipment.url=http://manager-application:8080
returntoken.url=http://manager-application:8080
