spring.application.name=returning-track-manager
##### Environment
logging.level.org.springframework.boot.context.config=DEBUG
spring.profiles.include=dev, mail, docker

##### Service discovery
eureka.client.enabled=${EUREKA_CLIENT_ENABLED:true}
eureka.client.service-url.defaultZone=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
eureka.client.healthcheck.enabled=true
eureka.instance.prefer-ip-address=${EUREKA_INSTANCE_PREFER_IP_ADDRESS:true}
eureka.instance.health-check-url-path=${server.servlet.contextPath}/actuator/health
eureka.instance.status-page-url-path=${server.servlet.contextPath}/actuator/info

##### Database configuration
spring.jpa.show-sql=true

##### Swagger
spring.mvc.pathmatch.matching-strategy= ANT_PATH_MATCHER

##### Kafka
spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
spring.kafka.consumer.group-id=${SPRING_KAFKA_CONSUMER_GROUP_ID:returning-track-manager}
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
manager.kafka.topics.shipment-return-created=${SHIPMENT_RETURN_CREATED_TOPIC:shipment.return.created}

##### Global prefix endpoint
server.servlet.contextPath=/v2/api

purge.cron.expression= @midnight

server.port=8070
