ALTER TABLE department
ADD COLUMN country_code VARCHAR(4) NOT NULL;

UPDATE department
SET country_code = CASE country
                       WHEN 'Albania' THEN 'AL'
                       WHEN 'Andora' THEN 'AD'
                       WHEN 'Austria' THEN 'AT'
                       WHEN 'Belgia' THEN 'BE'
                       WHEN 'Białoruś' THEN 'BY'
                       WHEN 'Bośnia i Hercegowina' THEN 'BA'
                       WHEN 'Bułgaria' THEN 'BG'
                       WHEN 'Chorwacja' THEN 'HR'
                       WHEN 'Czarnogóra' THEN 'ME'
                       WHEN 'Czechy' THEN 'CZ'
                       WHEN 'Dania' THEN 'DK'
                       WHEN 'Estonia' THEN 'EE'
                       WHEN 'Finlandia' THEN 'FI'
                       WHEN 'Francja' THEN 'FR'
                       WHEN 'Grecja' THEN 'GR'
                       WHEN 'Hiszpania' THEN 'ES'
                       WHEN 'Holandia' THEN 'NL'
                       WHEN 'Irlandia' THEN 'IE'
                       WHEN 'Islandia' THEN 'IS'
                       WHEN 'Kazachstan' THEN 'KZ'
                       WHEN 'Kosowo' THEN 'XK'
                       WHEN 'Liechtenstein' THEN 'LI'
                       WHEN 'Litwa' THEN 'LT'
                       WHEN 'Luksemburg' THEN 'LU'
                       WHEN 'Łotwa' THEN 'LV'
                       WHEN 'Macedonia Północna' THEN 'MK'
                       WHEN 'Malta' THEN 'MT'
                       WHEN 'Mołdawia' THEN 'MD'
                       WHEN 'Monako' THEN 'MC'
                       WHEN 'Niemcy' THEN 'DE'
                       WHEN 'Norwegia' THEN 'NO'
                       WHEN 'Polska' THEN 'PL'
                       WHEN 'Portugalia' THEN 'PT'
                       WHEN 'Rosja' THEN 'RU'
                       WHEN 'Rumunia' THEN 'RO'
                       WHEN 'San Marino' THEN 'SM'
                       WHEN 'Serbia' THEN 'RS'
                       WHEN 'Słowacja' THEN 'SK'
                       WHEN 'Słowenia' THEN 'SI'
                       WHEN 'Szwajcaria' THEN 'CH'
                       WHEN 'Szwecja' THEN 'SE'
                       WHEN 'Turcja' THEN 'TR'
                       WHEN 'Ukraina' THEN 'UA'
                       WHEN 'Watykan' THEN 'VA'
                       WHEN 'Węgry' THEN 'HU'
                       WHEN 'Wielka Brytania' THEN 'GB'
                       WHEN 'Włochy' THEN 'IT'
                       ELSE NULL
    END;
