CREATE TABLE country
(
    country_code VARCHAR(2)   NOT NULL PRIMARY KEY,
    name         VARCHAR(100) NOT NULL
);

INSERT INTO country (country_code, name)
VALUES ('AL', 'ALBANIA'),
       ('AD', 'ANDORRA'),
       ('AM', 'ARMENIA'),
       ('AT', 'AUSTRIA'),
       ('AZ', 'AZERBAIJAN'),
       ('BY', 'BELARUS'),
       ('BE', 'BELGIUM'),
       ('BA', 'BOSNIA_AND_HERZEGOVINA'),
       ('BG', 'BULGARIA'),
       ('HR', 'CROATIA'),
       ('CY', 'CYPRUS'),
       ('CZ', 'CZECH_REPUBLIC'),
       ('DK', 'DENMARK'),
       ('EE', 'ESTONIA'),
       ('FI', 'FINLAND'),
       ('FR', 'FRANCE'),
       ('GE', 'GEORGIA'),
       ('DE', 'GERMANY'),
       ('GR', 'GREECE'),
       ('HU', 'HUNGARY'),
       ('IS', 'ICELAND'),
       ('IE', 'IRELAND'),
       ('IT', 'ITALY'),
       ('KZ', 'KAZAKHSTAN'),
       ('XK', 'KOSOVO'),
       ('LV', 'LATVIA'),
       ('LI', 'LIECHTENSTEIN'),
       ('LT', 'LITHUANIA'),
       ('LU', 'LUXEMBOURG'),
       ('MT', 'MALTA'),
       ('MD', 'MOLDOVA'),
       ('MC', 'MONACO'),
       ('ME', 'MONTENEGRO'),
       ('NL', 'NETHERLANDS'),
       ('MK', 'NORTH_MACEDONIA'),
       ('NO', 'NORWAY'),
       ('PL', 'POLAND'),
       ('PT', 'PORTUGAL'),
       ('RO', 'ROMANIA'),
       ('RU', 'RUSSIA'),
       ('SM', 'SAN_MARINO'),
       ('RS', 'SERBIA'),
       ('SK', 'SLOVAKIA'),
       ('SI', 'SLOVENIA'),
       ('ES', 'SPAIN'),
       ('SE', 'SWEDEN'),
       ('CH', 'SWITZERLAND'),
       ('TR', 'TURKEY'),
       ('UA', 'UKRAINE'),
       ('GB', 'UNITED_KINGDOM'),
       ('VA', 'VATICAN_CITY');
