service.mock: true

redirect:
  token:
    body: |
      Docelowa destynacja paczki to: {} {} 
      Kod państwa paczki to: {}
      Aby pobrać etykietę prosimy wejść w {}
      Aby opłacić przesyłkę prosimy wejść w : {}
      Aby zarządzać przesyłką prosimy wejść w: {}
    subject: Żądanie o przekierowanie przesyłki

purge:
  cron:
    expression: "@midnight"